version: 1.0
provider:
  name: openfaas
  gateway: http://${GATEWAY_IP}:8080

functions:

  w3f-1kv-prometheus-exporter-kusama:
    lang: node12
    handler: ./1kv-prometheus-exporter
    image: derekc/w3f-1kv-prometheus-exporter:latest
    secrets:
    - dotenv
    environment:
      CHAIN: kusama
      exec_timeout: "90s"
  w3f-1kv-prometheus-exporter-polkadot:
    lang: node12
    handler: ./1kv-prometheus-exporter
    image: derekc/w3f-1kv-prometheus-exporter:latest
    secrets:
    - dotenv
    environment:
      CHAIN: polkadot
      exec_timeout: "90s"
